[pytest]
addopts = -s -ra -v -p no:warnings --tb=no -p no:metadata
  --env=sit --client=lirunex --server=mt4 --account=demo
  --platform=web --browser=chrome


testpaths = tests

python_functions =
    test_
    test*

python_files =
    test*