# GENERAL #


root_url: https://root.webtrader-releasesit.s20ip12.com/root
user_root: ...
password_root: ...

lirunex:
  base_url: https://lirunex-mb.webtrader-sit.s20ip12.com/web
  bo_url: https://lirunex-backoffice.webtrader-sit.s20ip12.com/backoffice

  credentials:
    mt4:
      user_live: 2092007779  # account demo, for sample
      password_live: 9Gp2#w51eSI$

      user_crm: ...
      password_crm: ...

      user_demo: 2092007779
      password_demo: 9Gp2#w51eSI$

    mt5:

      user_live: 569200612
      password_live: Master@123

      user_crm: ...
      password_crm: ...

      user_demo: 569200612
      password_demo: Master@123

  android_package: ...
  ios_bundle: ...

transactionCloud:
  base_url: https://transactcloudmt5-mb.webtrader-sit.s20ip12.com/web
  bo_url: https://transactcloudmt5-backoffice.webtrader-sit.s20ip12.com/backoffice/

  credentials:
    mt5:
      user_live: 998536
      password_live: lO##I3!epVa6

      user_demo: 998536
      password_demo: lO##I3!epVa6

  android_package: ...
  ios_bundle: ...
